{% set name = "abc-classroom" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc3d899cd0cc812283ec7423918dcf919a1fb014ec07d031a5f0c62c7fb5b710

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - nbclean
    - jinja2
    - nbformat
    - ruamel.yaml
    - github3.py
test:
  imports:
    - abcclassroom

about:
  home: http://github.com/earthlab/abc-classroom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package for managing student assignment repos in Github Classroom.

  description: |
    A set of command line commands that create template repos, push new content 
    to GitHub, collect student assignment repos and returns feedback. This package is maintained
    by Earth Lab.
  doc_url: http://abc-classroom.readthedocs.io/
  dev_url: https://github.com/earthlab/abc-classroom

extra:
  recipe-maintainers:
    - lwasser
